version: '3.8'

services:
  svg-php-app:
    build: .
    container_name: svg-php-launcher
    ports:
      - "${PORT:-8097}:80"
    volumes:
      - ./:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./output:/var/www/html/output
    environment:
      - APP_TITLE=${APP_TITLE:-SVG+PHP Application}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - APP_AUTHOR=${APP_AUTHOR:-Developer}
      - CALCULATOR_TITLE=${CALCULATOR_TITLE:-PHP Calculator}
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - db
    networks:
      - svg-php-network

  # Optional: Database for advanced features
  db:
    image: mysql:8.0
    container_name: svg-php-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-svgphp}
      MYSQL_USER: ${DB_USER:-svgphp}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - svg-php-network
    profiles:
      - production

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: svg-php-nginx
    ports:
      - "${NGINX_PORT:-8098}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    depends_on:
      - svg-php-app
    networks:
      - svg-php-network
    profiles:
      - production

volumes:
  db_data:

networks:
  svg-php-network:
    driver: bridge
